spring.mvc.view:
  prefix: '/WEB-INF/view/'
  suffix: '.jsp'

shop:
  properties:
    products:
      - product:
        id: 1
        title: 'Phone1'
        cost: 10.0
      - product:
        id: 2
        title: 'Phone2'
        cost: 20.0
      - product:
        id: 3
        title: 'Phone3'
        cost: 30.0
      - product:
        id: 4
        title: 'Phone4'
        cost: 20.0
      - product:
        id: 5
        title: 'Phone5'
        cost: 30.0